FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --frozen-lockfile
COPY . .
RUN npm run build -- --configuration=production
FROM nginx:stable-alpine AS production
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN mkdir -p /var/cache/nginx /var/run /etc/nginx/conf.d /run && \
    chown -R appuser:appgroup /var/cache/nginx /var/run /etc/nginx /usr/share/nginx/html /run
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/web/browser/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN chown -R appuser:appgroup /usr/share/nginx/html
USER appuser
EXPOSE 8001
CMD ["nginx", "-g", "daemon off;"]
