# Generated by Django 5.1.7 on 2025-03-30 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=255)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldtype')),
            ],
        ),
        migrations.CreateModel(
            name='ListField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldtype')),
            ],
        ),
        migrations.CreateModel(
            name='ListFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fieldtyperule')),
                ('list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listfield')),
            ],
        ),
        migrations.CreateModel(
            name='ListItemField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(max_length=255)),
                ('list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listfield')),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_read_only', models.BooleanField(default=False)),
                ('is_checkable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.moduletype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listitem',
            name='user_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodule'),
        ),
        migrations.AddField(
            model_name='listfield',
            name='user_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodule'),
        ),
    ]
