# Generated by Django 5.1.7 on 2025-03-31 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='fields',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ListFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=255)),
                ('list_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.listfield')),
            ],
        ),
        migrations.DeleteModel(
            name='ListItemField',
        ),
    ]
