# Generated by Django 5.1.7 on 2025-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listitem_fields_listfieldoption_delete_listitemfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='listfield',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
