# Generated by Django 5.1.7 on 2025-05-07 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_listfield_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('weekly_target', models.IntegerField(default=0)),
                ('excluded_from_budget', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodule')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('user_module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BudgetPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.budgetcategory')),
                ('user_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodule')),
            ],
            options={
                'ordering': ['-purchase_date', '-modified_at'],
            },
        ),
    ]
