# Generated by Django 5.1.7 on 2025-05-29 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_period_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTermType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_length', models.IntegerField(unique=True)),
                ('weight', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['word_length'], name='idx_termtype_wordlength')],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategoryTermFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.budgetcategory')),
                ('term_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.budgettermtype')),
            ],
            options={
                'indexes': [models.Index(fields=['term_type', 'term'], name='idx_termtype_term'), models.Index(fields=['category', 'term_type'], name='idx_category_termtype')],
                'unique_together': {('category', 'term', 'term_type')},
            },
        ),
    ]
