# Generated by Django 5.1.7 on 2026-03-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_term_type_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['order', '-modified_at']},
        ),
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
