# Generated by Django 5.1.7 on 2026-03-13 15:35

from django.db import migrations


def set_initial_order(apps, schema_editor):
    ListItem = apps.get_model('api', 'ListItem')
    UserModule = apps.get_model('api', 'UserModule')
    
    # Get all list modules
    list_modules = UserModule.objects.filter(module__name='list')
    
    for module in list_modules:
        # Get all list items for this module, sorted by ID (creation order)
        items = ListItem.objects.filter(user_module=module).order_by('id')
        
        # Set order sequentially
        for idx, item in enumerate(items):
            item.order = idx + 1
            item.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_listitem_options_listitem_order'),
    ]

    operations = [
        migrations.RunPython(set_initial_order, reverse_code=migrations.RunPython.noop),
    ]
