# Generated by Django 5.1.7 on 2026-03-15 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_populate_listitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetBulkImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(default=list)),
                ('mapping', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usermodule')),
            ],
        ),
    ]
