FROM python:3.12-alpine AS builder
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
WORKDIR /app
RUN apk add --no-cache \
    build-base \
    python3-dev \
    postgresql-dev \
    libffi-dev \
    jpeg-dev \
    zlib-dev
COPY requirements.txt .
RUN pip install --prefix=/install --no-cache-dir -r requirements.txt
FROM python:3.12-alpine
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
WORKDIR /app
RUN apk add --no-cache \
    libpq \
    libjpeg \
    zlib \
    libffi
COPY --from=builder /install /usr/local
COPY . .
RUN python manage.py collectstatic --noinput
RUN chown -R appuser:appgroup /app
RUN mkdir -p /lifeapi_logs && chown -R appuser:appgroup /lifeapi_logs
USER appuser
CMD ["sh", "-c", "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000"]
